web:
  upload-path: upload/uploadFiles/
  upload-url: http://120.78.205.51:7073/upload/

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

server:
  port: 7073